FROM python:3.12
WORKDIR /code
COPY ./requirements.txt /code/requirements.txt
RUN pip install -no-cache-dir -- upgrade -requirements/code/requirements.txt
COPY ./shift_devops_aula/app /code/app
CMD ["fastapi", "run", "app/main.py", "--port", "80"]